[package]
name = "RUSTYFASTSTRINGTHING"
version = "0.1.0"
authors = ["khk"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unic-normal = "0.9.0"
regex = "1.4.1"
lazy_static = "1.4.0"
